export * from "./ir/types.js";
export * from "./config/defaultConfig.js";
export * from "./parser/parseMarkdown.js";
export * from "./outline/buildOutlineTree.js";
export * from "./split/density.js";
export * from "./split/splitPlanner.js";
export * from "./intent/detectSlideIntent.js";
export * from "./utils/stableId.js";
export * from "./theme/designPresets.js";
